"""update

Revision ID: 6f0e3c384a85
Revises: 
Create Date: 2023-12-23 20:42:07.172889

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6f0e3c384a85"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "musik",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_buku")),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=True),
        sa.Column("password", sa.Text(), nullable=True),
        sa.Column("email", sa.String(length=255), nullable=True),
        sa.Column("role", sa.Text(), nullable=True),
        sa.Column("token", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user")),
        sa.UniqueConstraint("email", name=op.f("uq_user_email")),
    )
    op.create_index("user_email", "user", ["email"], unique=True, mysql_length=255)

    op.bulk_insert(
        sa.table(
            "user",
            sa.Column("name", sa.Text(), nullable=True),
            sa.Column("password", sa.Text(), nullable=True),
            sa.Column("email", sa.String(length=255), nullable=True),
            sa.Column("role", sa.Text(), nullable=True),
            sa.Column("token", sa.Text(), nullable=True),
        ),
        [
            {
                "name": "admin",
                "password": "admin",
                "email": "admin@admin.com",
                "role": "admin",
                "token": "",
            },
            {
                "name": "user",
                "password": "user",
                "email": "user@user.com",
                "role": "user",
                "token": "",
            },
        ],
    )

    op.bulk_insert(
        sa.table(
            "musik",
            sa.Column("title", sa.Text(), nullable=True),
            sa.Column("description", sa.Text(), nullable=True),
            sa.Column("year", sa.Integer(), nullable=True),
        ),
        [
            {
                "title": "Bohemian Rhapsody",
                "description": "Lagu klasik dari band Queen, dianggap sebagai salah satu lagu paling ikonik sepanjang masa.",
                "year": 1975,
            },
            {
                "title": "Thriller",
                "description": "Album studio keenam dari Michael Jackson yang merupakan salah satu album terlaris sepanjang masa.",
                "year": 1982,
            },
            {
                "title": "Hotel California",
                "description": "Lagu hits dari band Eagles yang menjadi salah satu lagu paling terkenal dalam sejarah musik rock.",
                "year": 1976,
            },
            {
                "title": "Back in Black",
                "description": "Album yang ikonik dari AC/DC, salah satu album rock paling sukses dalam sejarah.",
                "year": 1980,
            },
            {
                "title": "The Dark Side of the Moon",
                "description": "Album studio dari band Pink Floyd yang dianggap sebagai salah satu album terbaik dalam sejarah musik.",
                "year": 1973,
            },
            {
                "title": "Abbey Road",
                "description": "Album terakhir yang direkam oleh The Beatles meskipun dirilis sebelum Let It Be.",
                "year": 1969,
            },
            {
                "title": "Back to Black",
                "description": "Album studio kedua dari Amy Winehouse yang meraih banyak pujian kritis.",
                "year": 2006,
            },
            {
                "title": "Rumours",
                "description": "Album studio dari Fleetwood Mac yang menjadi salah satu album terlaris sepanjang masa.",
                "year": 1977,
            },
            {
                "title": "Born to Run",
                "description": "Album dari Bruce Springsteen yang mengukuhkannya sebagai salah satu artis rock paling berpengaruh.",
                "year": 1975,
            },
            {
                "title": "Purple Rain",
                "description": "Album soundtrack dari Prince yang meraih kesuksesan komersial dan kritis yang besar.",
                "year": 1984,
            },
        ],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("user_email", table_name="user", mysql_length=255)
    op.drop_table("user")
    op.drop_table("musik")
    # ### end Alembic commands ###
